### ISSUE TITLE
pygobject/XApp.py fails with new pygobject.

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/xapps#47]
After upgrading to Gnome 3.30 libs (most likely because of update to pygobject-3.30 ) pygobject/XApp.py fails to load with following backtrace
```
$ python3
Python 3.6.5 (default, Jun  8 2018, 06:42:37) 
[GCC 7.3.1 20180303 (ALT 7.3.1-alt4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import XApp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib64/python3/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib64/python3/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib64/python3/site-packages/gi/overrides/XApp.py", line 21, in <module>
    class GtkWindow(XApp.GtkWindow):
  File "/usr/lib64/python3/site-packages/gi/module.py", line 215, in __getattr__
    wrapper = metaclass(name, bases, dict_)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

And because of this fail cinnamon-settings also crashes.

**Comment by leigh123linux** [comment]
Your issue is related to https://gitlab.gnome.org/GNOME/atk/issues/1
