### ISSUE TITLE
xapp-sn-watcher crashes while booting if notebook boots without power cable

### ISSUE THREAD

**Issue by jdepi** [linuxmint/xapps#99]
Dear all,
I have a very new HP Laptop 15s eq0 with bios from april, 2020 and a Ryzen 5 3500U inside.
I installed LinuxMint 20 and everything looks fine, Mint is installed and customized, kernel 5.4.0-39-generic x86_64 is running, but:
if I disconnect the power cable and boot the laptop I will get a black screen instead of a login screen. After waiting a minute I powered off the machine, connected the power cable and booting worked fine again. This behaviour is reproduceable.
I am not shure if I have forced the following crash because of powering off the machine, but this was the only way to get the machine running.
You can find an indicator of this crash, hopefully:
===================================================================
 Info                                                              
===================================================================
           PID: 1643 (xapp-sn-watcher)
           UID: 1000 (xx)
           GID: 1000 (xx)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-06-29 18:22:51 CEST (39s ago)
  Command Line: /usr/libexec/xapps/sn-watcher/xapp-sn-watcher
    Executable: /usr/libexec/xapps/sn-watcher/xapp-sn-watcher
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (xx)
       Boot ID: xx
    Machine ID: xx
      Hostname: HP-Laptop-15s-eq0xxx
       Storage: /var/lib/systemd/coredump/core.xapp-sn-watcher.1000.58c2cb0253664136a353e25501762439.1643.1593447771000000000000.lz4
       Message: Process 1643 (xapp-sn-watcher) of user 1000 dumped core.
                
                Stack trace of thread 1643:
                #0  0x00007f6d0bdfb6e4 n/a (libglib-2.0.so.0 + 0x876e4)
                #1  0x00007f6d0bdfbb90 g_utf8_normalize (libglib-2.0.so.0 + 0x87b90)
                #2  0x00005634255f81c7 n/a (xapp-sn-watcher + 0x131c7)
                #3  0x00007f6d0bfb1f49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #4  0x00007f6d0bfb2b3d n/a (libgio-2.0.so.0 + 0xb5b3d)
                #5  0x00007f6d0c01885d n/a (libgio-2.0.so.0 + 0x11b85d)
                #6  0x00007f6d0bfb1f49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #7  0x00007f6d0bfb2b3d n/a (libgio-2.0.so.0 + 0xb5b3d)
                #8  0x00007f6d0c017e71 n/a (libgio-2.0.so.0 + 0x11ae71)
                #9  0x00007f6d0c017fac n/a (libgio-2.0.so.0 + 0x11afac)
                #10 0x00007f6d0bfb1f49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #11 0x00007f6d0bfb2b3d n/a (libgio-2.0.so.0 + 0xb5b3d)
                #12 0x00007f6d0c00d31f n/a (libgio-2.0.so.0 + 0x11031f)
                #13 0x00007f6d0bfb1f49 n/a (libgio-2.0.so.0 + 0xb4f49)
                #14 0x00007f6d0bfb1f8d n/a (libgio-2.0.so.0 + 0xb4f8d)
                #15 0x00007f6d0bdc5e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #16 0x00007f6d0bdc6240 n/a (libglib-2.0.so.0 + 0x52240)
                #17 0x00007f6d0bdc62e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #18 0x00007f6d0bfdffd5 g_application_run (libgio-2.0.so.0 + 0xe2fd5)
                #19 0x00005634255eeda8 main (xapp-sn-watcher + 0x9da8)
                #20 0x00007f6d0b1930b3 __libc_start_main (libc.so.6 + 0x270b3)
                #21 0x00005634255eee0e _start (xapp-sn-watcher + 0x9e0e)
                
                Stack trace of thread 1677:
                #0  0x00007f6d0b28196f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f6d0bdc61ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f6d0bdc6533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f6d0c01be9a n/a (libgio-2.0.so.0 + 0x11ee9a)
                #4  0x00007f6d0bdef931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f6d0af1d609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f6d0b28e103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1674:
                #0  0x00007f6d0b28196f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f6d0bdc61ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f6d0bdc62e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f6d0bdc6331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f6d0bdef931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f6d0af1d609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f6d0b28e103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1675:
                #0  0x00007f6d0b28196f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f6d0bdc61ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f6d0bdc62e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f6d0c11899d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f6d0bdef931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f6d0af1d609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f6d0b28e103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1864:
                #0  0x00007f6d0b28770d syscall (libc.so.6 + 0x11b70d)
                #1  0x00007f6d0be135a6 g_cond_wait_until (libglib-2.0.so.0 + 0x9f5a6)
                #2  0x00007f6d0bd96561 n/a (libglib-2.0.so.0 + 0x22561)
                #3  0x00007f6d0bd96b86 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x22b86)
                #4  0x00007f6d0bdf0279 n/a (libglib-2.0.so.0 + 0x7c279)
                #5  0x00007f6d0bdef931 n/a (libglib-2.0.so.0 + 0x7b931)
                #6  0x00007f6d0af1d609 start_thread (libpthread.so.0 + 0x9609)
                #7  0x00007f6d0b28e103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1643]
[New LWP 1677]
[New LWP 1674]
[New LWP 1675]
[New LWP 1864]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/xapps/sn-watcher/xapp-sn-watcher'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6d0bdfb6e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f6d07ff5a80 (LWP 1643))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1643]
[New LWP 1677]
[New LWP 1674]
[New LWP 1675]
[New LWP 1864]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/xapps/sn-watcher/xapp-sn-watcher'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6d0bdfb6e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f6d07ff5a80 (LWP 1643))]
#0  0x00007f6d0bdfb6e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f6d0bdfbb90 in g_utf8_normalize () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00005634255f81c7 in ?? ()
#3  0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007f6d0c01885d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f6d0c017e71 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007f6d0c017fac in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x00007f6d0c00d31f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007f6d0bfb1f8d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007f6d0bdc5e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f6d0bdc6240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f6d0bdc62e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f6d0bfdffd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x00005634255eeda8 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1643]
[New LWP 1677]
[New LWP 1674]
[New LWP 1675]
[New LWP 1864]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/xapps/sn-watcher/xapp-sn-watcher'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6d0bdfb6e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f6d07ff5a80 (LWP 1643))]

Thread 5 (Thread 0x7f6d05ffc700 (LWP 1864)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f6d0be135a6 in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f6d0bd96561 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f6d0bd96b86 in g_async_queue_timeout_pop () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f6d0bdf0279 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f6d0bdef931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007f6d0af1d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140106228811520, 2737129514704051444, 140725383249342, 140725383249343, 140725383249488, 140106228808832, -2655374225830044428, -2655389674095371020}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007f6d0b28e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7f6d0779f700 (LWP 1675)):
#0  0x00007f6d0b28196f in __GI___poll (fds=0x56342671b8b0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f6d0bdc61ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f6d0bdc62e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f6d0c11899d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f6d0bdef931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f6d0af1d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140106253596416, 2737129514704051444, 140725383250254, 140725383250255, 140725383250400, 140106253593728, -2655379707818926860, -2655389674095371020}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f6d0b28e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f6d07fa0700 (LWP 1674)):
#0  0x00007f6d0b28196f in __GI___poll (fds=0x5634267180d0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f6d0bdc61ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f6d0bdc62e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f6d0bdc6331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f6d0bdef931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f6d0af1d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140106261989120, 2737129514704051444, 140725383249870, 140725383249871, 140725383250016, 140106261986432, -2655378608844169996, -2655389674095371020}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f6d0b28e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f6d0693e700 (LWP 1677)):
#0  0x00007f6d0b28196f in __GI___poll (fds=0x7f6cf8017af0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f6d0bdc61ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f6d0bdc6533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f6d0c01be9a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f6d0bdef931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f6d0af1d609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140106238519040, 2737129514704051444, 140106253592590, 140106253592591, 140106253592736, 140106238516352, -2655380035847054092, -2655389674095371020}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f6d0b28e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f6d07ff5a80 (LWP 1643)):
#0  0x00007f6d0bdfb6e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007f6d0bdfbb90 in g_utf8_normalize () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00005634255f81c7 in ?? ()
No symbol table info available.
#3  0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#5  0x00007f6d0c01885d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#6  0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#7  0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#8  0x00007f6d0c017e71 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#9  0x00007f6d0c017fac in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#10 0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#11 0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#12 0x00007f6d0c00d31f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#13 0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#14 0x00007f6d0bfb1f8d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#15 0x00007f6d0bdc5e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#16 0x00007f6d0bdc6240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#17 0x00007f6d0bdc62e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0x00007f6d0bfdffd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#19 0x00005634255eeda8 in main ()
No symbol table info available.
#0  0x00007f6d0bdfb6e4 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f6d0bdfbb90 in g_utf8_normalize () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00005634255f81c7 in ?? ()
#3  0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x00007f6d0c01885d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f6d0c017e71 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007f6d0c017fac in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007f6d0bfb2b3d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x00007f6d0c00d31f in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007f6d0bfb1f49 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007f6d0bfb1f8d in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007f6d0bdc5e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f6d0bdc6240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f6d0bdc62e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007f6d0bfdffd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x00005634255eeda8 in main ()

**Comment by leigh123linux** [comment]
Duplicate #98

**Comment by mtwebster** [comment]
If you're never even reaching the login screen, then this xapp crash is unrelated (and relatively minor) - this program only starts after login.  I'm not sure what could be causing it, though.  Do you see anything helpful if you hit escape while the mint splash screen is showing (if it gets that far)?
